### ISSUE TITLE
rdet blocks backtrace

### ISSUE THREAD

**Issue by kamahen** [rla/rdet#4]
I've discovered that I need to make this change to rdet, to get a backtrace:
```diff
@@ -80,7 +80,7 @@
     Functor = Name/Arity,
     debug(rdet, 'rdet: rewriting goal ~w at ~w', [Functor, At]),
     Out = ( Goal -> true
-          ; throw(error(goal_failed(Functor, At)))).
+          ; throw(error(goal_failed(Functor, At), _))).
 
 % Produces goal marker which is the byte
 % position of the last read term.
```

I also have these set in my main predicate, but don't know if they're needed:
```prolog
    set_prolog_flag(report_error, true),
    set_prolog_flag(backtrace, true),
    set_prolog_flag(backtrace_show_lines, true),
    catch_with_backtrace(main2,
                         Error,
                         ( print_message(error, Error),
                           halt(1) )),
    halt(0).
```

**Comment by rla** [comment]
Sorry for a long overdue reaction to this. The errors do need placeholder argument for stacktrace. When I wrote this package, I did not yet know about this practice. I'm adding this placeholder to all errors that the library throws.

Recent versions of SWI have these prolog flags configured by default. I checked with 7.7.22.

**Comment by rla** [comment]
All errors now have necessary 2nd variable argument to make use of backtraces. Tested with 8.1.15. All works there. Closing.
