### ISSUE TITLE
Setup benchmarking

### ISSUE THREAD

**Issue by rla** [rla/rdet#6]
We need to benchmark different goal expansion schemes as described in #5. The Makefile should contain a target for this that runs benchmarking (with -O and without) and reports the result on the standard output.

**Comment by rla** [comment]
Running `make benchmark` will now provide benchmarking output.

**Comment by kamahen** [comment]
FWIW, when I tried turning rdet on/off in my code, the speed difference was in the "noise" (my benchmarks tend to vary about +/-5%, sometimes more, even though they're about 90% CPU). My code is mostly deterministic (the few non-deterministic goals are mainly tests or shallow backtracking generators), so the "cut" in the goal expansion usually doesn't remove a choice point. YMMV of course.
