### ISSUE TITLE
Install broken with SWI-Prolog 8.1.15

### ISSUE THREAD

**Issue by kamahen** [rla/rdet#8]
SWI-Prolog 8.1.15 has moved configuration and library files. This seems to have broken the install:
```
$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.1.15)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- pack_install(rdet).
% Contacting server at https://www.swi-prolog.org/pack/query ... ok
Install rdet@0.0.2 from GIT at https://github.com/rla/rdet.git Y/n? 
% Cloning into '/home/peter/.local/share/swi-prolog/pack/rdet'...
% Contacting server at https://www.swi-prolog.org/pack/query ... ok
% "rdet.git" was downloaded 19 times
Package:                rdet
Title:                  Runtime determinacy checker
Installed version:      0.0.2
Author:                 Raivo Laanemets <http://rlaanemets.com/>
Home page:              https://github.com/rla/rdet
Run post installation scripts for pack "rdet" Y/n? 
% make: *** No rule to make target 'all'.  Stop.
ERROR: Process "process(path(make),[all])": exit status: 2
ERROR: In:
ERROR:   [20] throw(error(process_error(...,...),_46062))
ERROR:   [18] '$apply':forall(prolog_pack:member(all,...),prolog_pack:run_process(...,...,...)) at /usr/lib/swi-prolog/boot/apply.pl:52
ERROR:   [14] prolog_pack:pack_post_install(rdet,'/home/peter/.local/share/swi-prolog/pack/rdet',[git(true),...|...]) at /usr/lib/swi-prolog/library/prolog_pack.pl:1017
ERROR:    [9] <user>
ERROR: 
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
```

**Comment by rla** [comment]
@kamahen, seems like it tries to run `make all`. I do have a Makefile in pack but only to help publish the pack. I think that previously it only ran Makefile if it had postinstall target (not sure how it figured that out tho).

I will come up with something that does not involve Makefile and I will try to bring it up in SWI Discourse. Maybe we will get something like `postinstall(make(target))` in `pack.pl` that would clarify post-install commands or actions.

It likely means I have to go over all my packs as all of them use Makefile.

**Comment by rla** [comment]
@kamahen, I published a new version (1.0.0) of the pack that now comes from HTTP host again. I see that this error is coming because version 0.0.2 was installed from GitHub. It requires further research why pack installation from a web server vs git differs.

**Comment by kamahen** [comment]
I was unable to upgrade the pack (`pack_install(rdet, [upgrad(true)]).` -- the response was that version 0.0.2 was already installed); I had to manually delete the files and then I could install 1.0.0. Maybe this is a bug in `pack_install`? Maybe because of the different repositories? (I don't know enough about `pack_install` to do anything other than wild speculation.)

**Comment by kamahen** [comment]
I ended up doing `pack_remove(rdet).` and then it installed fine. (I had to make quite a few changes to my code, but that wasn't difficult.)

**Comment by rla** [comment]
I added empty `all`, `check`, and `install` targets to the Makefile. Installing from git now works without error. I have no idea how upgrade is supposed to work.

If you want to be sure, then just use git submodules and `attach_packs`. For example, I have all packs in `/home/raivo/pack` and this is in my `~/.config/swi-prolog/init.pl`:

```
:- attach_packs('/home/raivo/pack', _{duplicate: replace}).
```

**Comment by kamahen** [comment]
My suspicion is that "upgrade" is partially broken. I have a few questions pending in the main SWI-Prolog list, but I don't have time (or desire) to dig into this. For now, my solution is to just do a `pack_remove` followed by `pack_install` to ensure I get the latest version.
